---
services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs:ro
      - ./dynamic:/dynamic:ro

    command:
      # EntryPoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"

      # Attach the static configuration tls.yaml file that contains the tls configuration settings
      - "--providers.file.filename=/dynamic/tls.yaml"

      # Providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"

      # API & Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Observability
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--metrics.prometheus=true"

    # Traefik Dynamic configuration via Docker labels
    labels:
      # Enable self‑routing
      - "traefik.enable=true"

      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.docker.localhost`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

      # Basic‑auth middleware
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$$apr1$$s3C5htrG$$mQGTNpcq0qYhK.jdvFFkU0"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

  web:
    image: kbcs-web:latest
    container_name: kbcs-web
    networks:
      - proxy
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.docker.localhost`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.service.web.loadbalancer.server.port=80"

  admin:
    image: kbcs-admin:latest
    container_name: kbcs-admin
    networks:
      - proxy
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.docker.localhost`)"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.routers.admin.tls=true"
      - "traefik.service.admin.loadbalancer.server.port=80"

  server:
    image: kbcs-server:latest
    container_name: kbcs-server
    networks:
      - proxy
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`server.docker.localhost`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls=true"
      - "traefik.service.server.loadbalancer.server.port=5000"

networks:
  proxy:
    name: proxy