"""Added status property to Seller model

Revision ID: a9027b4b003c
Revises: c2cc97b6a73b
Create Date: 2026-06-04 20:32:02.701700

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "a9027b4b003c"
down_revision = "c2cc97b6a73b"
branch_labels = None
depends_on = None


def upgrade():
    # Step 1: Add the column as nullable
    with op.batch_alter_table("seller", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum("Active", "Inactive", name="sellerstatus"),
                nullable=True,
            )
        )

    # Step 2: Backfill existing rows AFTER the column exists
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE seller SET status = 'Active'"))

    # Step 3: Now make it non-nullable
    with op.batch_alter_table("seller", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.Enum("Active", "Inactive", name="sellerstatus"),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("seller", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
