"""Updated Car model

Revision ID: c2cc97b6a73b
Revises: e3936923181f
Create Date: 2026-06-04 16:20:44.022197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2cc97b6a73b'
down_revision = 'e3936923181f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('fuelType',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Enum('gasoline', 'electric', 'hybrid', 'diesel', name='carfueltype'),
               existing_nullable=False)
        batch_op.alter_column('transmission',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Enum('automatic', 'manual', name='cartransmission'),
               existing_nullable=False)
        batch_op.alter_column('bodyType',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Enum('suv', 'sedan', 'coupe', 'truck', 'hatchback', 'convertible', 'van', 'wagon', name='carbodytype'),
               existing_nullable=False)
        batch_op.alter_column('condition',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Enum('excellent', 'very_good', 'good', name='carcondition'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('condition',
               existing_type=sa.Enum('excellent', 'very_good', 'good', name='carcondition'),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('bodyType',
               existing_type=sa.Enum('suv', 'sedan', 'coupe', 'truck', 'hatchback', 'convertible', 'van', 'wagon', name='carbodytype'),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('transmission',
               existing_type=sa.Enum('automatic', 'manual', name='cartransmission'),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('fuelType',
               existing_type=sa.Enum('gasoline', 'electric', 'hybrid', 'diesel', name='carfueltype'),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
