"""Updated seller id to be nullable

Revision ID: e3936923181f
Revises: 
Create Date: 2026-06-02 19:17:00.703096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3936923181f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('sellerId',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.alter_column('sellerId',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
