import {
  CarBodyType,
  CarCondition,
  CarFuelType,
  CarStatus,
  CarTransmission,
} from "@repo/shared";
import { ActivityLog, Car } from "./types";

export const INITIAL_CARS: Car[] = [
  {
    id: "car-1",
    status: "Available" as CarStatus,
    make: "Tesla",
    model: "Model 3",
    year: 2022,
    price: 38400,
    mileage: 18200,
    fuelType: "Electric" as CarFuelType,
    transmission: "Automatic" as CarTransmission,
    bodyType: "Sedan" as CarBodyType,
    exteriorColor: "Pearl White Multi-Coat",
    interiorColor: "All Black premium",
    engine: "Dual Motor All-Wheel Drive",
    drivetrain: "AWD",
    features: [
      "Autopilot",
      "Panoramic Glass Roof",
      "Heated Seats (Front & Rear)",
      "15-inch Touchscreen",
      "Premium Audio System",
      "Wireless Charging",
      "Sentry Mode",
    ],
    description:
      "Immaculate single-owner Tesla Model 3 Long Range. Featuresdual motor AWD, outstanding battery health (96% capacity), and full premium interior. Garaged daily, charging mostly done at home. Autopilot is included, and physical tires are in excellent condition.",
    imageUrl: "https://picsum.photos/seed/tesla3/800/600",
    condition: "Excellent" as CarCondition,
    seller: {
      id: "seller-1",
      name: "Eleanor Vance",
      phone: "(415) 555-0182",
      email: "eleanor.v@ev-owners.com",
      location: "San Francisco, CA",
      status: "active",
    },
  },
  {
    id: "car-2",
    status: "Sold" as CarStatus.Sold,
    make: "BMW",
    model: "M4 Coupe",
    year: 2021,
    price: 64900,
    mileage: 24500,
    fuelType: "Gasoline" as CarFuelType,
    transmission: "Manual" as CarTransmission,
    bodyType: "Coupe" as CarBodyType,
    exteriorColor: "Isle of Man Green Metallic",
    interiorColor: "Kyalami Orange Full Merino Leather",
    engine: "3.0L TwinPower Turbo I6",
    drivetrain: "RWD",
    features: [
      "M Carbon Bucket Seats",
      "Executive Package",
      "Harman Kardon Surround Sound",
      "M Adaptive Suspension",
      "Carbon Fiber Interior Trim",
      "Head-Up Display",
      "Apple CarPlay/Android Auto",
    ],
    description:
      "Stunning 2021 BMW M4 in the highly coveted Isle of Man Green over Kyalami Orange leather. Enthusiast-spec 6-speed manual transmission. Thoroughly loved, completely stock, with zero track time. PPF applied on the front bumper and hood.",
    imageUrl: "https://picsum.photos/seed/bmwm4/800/600",
    condition: "Excellent" as CarCondition,
    seller: {
      id: "seller-2",
      name: "Apex Motor Group",
      phone: "(650) 555-0194",
      email: "sales@apexmotorgroup.com",
      location: "Redwood City, CA",
      status: "active",
    },
  },
  {
    id: "car-3",
    status: "Archived" as CarStatus,
    make: "Porsche",
    model: "911 Carrera S",
    year: 2018,
    price: 94500,
    mileage: 31200,
    fuelType: "Gasoline" as CarFuelType,
    transmission: "Automatic" as CarTransmission,
    bodyType: "Coupe" as CarBodyType,
    exteriorColor: "GT Silver Metallic",
    interiorColor: "Bordeaux Red Leather",
    engine: "3.0L Twin-Turbo Flat-6",
    drivetrain: "RWD",
    features: [
      "Sport Chrono Package",
      "Sport Exhaust System",
      "PASM Sport Suspension",
      "20/21-inch Carrera S Wheels",
      "Bose Surround Sound",
      "14-Way Power Sport Seats",
    ],
    description:
      "A masterpiece of precision engineering. This 991.2 generation Carrera S features PDK dual-clutch transmission, active suspension, and the iconic Bordeaux Red leather interior. Perfect paint, professionally detailed quarterly.",
    imageUrl: "https://picsum.photos/seed/porsche911/800/600",
    condition: "Excellent" as CarCondition,
    seller: {
      id: "seller-3",
      name: "Prestige Auto Boutique",
      phone: "(310) 555-0143",
      email: "contact@prestigeautoboutique.com",
      location: "Beverly Hills, CA",
      status: "active",
    },
  },
  {
    id: "car-4",
    status: "Available" as CarStatus,
    make: "Toyota",
    model: "GR86",
    year: 2023,
    price: 31500,
    mileage: 8900,
    fuelType: "Gasoline" as CarFuelType,
    transmission: "Manual" as CarTransmission,
    bodyType: "Coupe" as CarBodyType,
    exteriorColor: "Trueno Blue",
    interiorColor: "Black Fabric with Red Stitching",
    engine: "2.4L Naturally Aspirated Flat-4",
    drivetrain: "RWD",
    features: [
      "Track Mode",
      "Performance Data Recorder",
      "Torsen Limited-Slip Differential",
      "18-inch BBS Wheels",
      "Apple CarPlay/Android Auto",
      "Dual-Zone Climate Control",
      "Brembo Brakes",
    ],
    description:
      "Low-mileage 2023 Toyota GR86 in the striking Trueno Blue exclusive color. Six-speed manual with a rev-happy FA24 boxer engine. Never tracked, no modifications, garage-kept since purchase. A purist's lightweight sports coupe in exceptional condition.",
    imageUrl: "https://picsum.photos/seed/toyotagr86/800/600",
    condition: "Excellent" as CarCondition,
    seller: {
      id: "seller-4",
      name: "Marcus Hale",
      phone: "(503) 555-0217",
      email: "marcus.hale@gr-drivers.com",
      location: "Portland, OR",
      status: "inactive",
    },
  },
  {
    id: "car-5",
    status: "Available" as CarStatus,
    make: "Ford",
    model: "Mustang GT",
    year: 2020,
    price: 41200,
    mileage: 22100,
    fuelType: "Gasoline" as CarFuelType,
    transmission: "Automatic" as CarTransmission,
    bodyType: "Coupe" as CarBodyType,
    exteriorColor: "Twister Orange Metallic",
    interiorColor: "Ebony Leather with Orange Accent Stitching",
    engine: "5.0L Coyote V8",
    drivetrain: "RWD",
    features: [
      "Performance Pack Level 1",
      "Active Valve Exhaust",
      "MagneRide Damping System",
      "Recaro Sport Seats",
      "B&O Sound System",
      "Launch Control",
      "Ford Co-Pilot360",
    ],
    description:
      "Head-turning 2020 Mustang GT with the Performance Pack Level 1 — a serious factory-tuned package with MagneRide suspension and Recaro seats. Single owner, highway miles, and completely stock. The Active Valve Exhaust has never disappointed.",
    imageUrl: "https://picsum.photos/seed/mustanggt/800/600",
    condition: "Good" as CarCondition,
    seller: {
      id: "seller-5",
      name: "Riverside Classic Cars",
      phone: "(714) 555-0368",
      email: "sales@riversideclassiccars.com",
      location: "Anaheim, CA",
      status: "inactive",
    },
  },
];

export const INITIAL_LOGS: ActivityLog[] = [
  {
    id: "log-1",
    timestamp: "15:11:04",
    type: "view",
    carId: "car-1",
    carName: "Tesla Model 3",
    message: "User from San Francisco, CA viewed Tesla Model 3",
    userLocation: "San Francisco, CA",
  },
  {
    id: "log-2",
    timestamp: "15:13:22",
    type: "search",
    carName: "All Cars",
    message: 'Anonymous user searched for "Electric" bodyType "Sedan"',
    userLocation: "Seattle, WA",
  },
  {
    id: "log-3",
    timestamp: "15:15:40",
    type: "enquiry",
    carId: "car-4",
    carName: "Porsche 911 Carrera",
    message:
      "Lead sent to Richard Foster regarding specs of Porsche 911 Carrera",
    userLocation: "Los Angeles, CA",
  },
  {
    id: "log-4",
    timestamp: "15:18:12",
    type: "view",
    carId: "car-3",
    carName: "Toyota RAV4 Hybrid",
    message: "User from Denver, CO viewed Toyota RAV4 Hybrid",
    userLocation: "Denver, CO",
  },
  {
    id: "log-5",
    timestamp: "15:19:55",
    type: "update",
    carId: "car-2",
    carName: "Ford F-150 Lightning",
    message:
      "CMS Agent updated price of Ford F-150 Lightning from $65,500 to $64,900",
    userLocation: "Austin, TX",
  },
];

export const US_LOCATIONS = [
  "San Francisco, CA",
  "Austin, TX",
  "Seattle, WA",
  "Los Angeles, CA",
  "Denver, CO",
  "Boston, MA",
  "Miami, FL",
  "Chicago, IL",
  "New York, NY",
  "Portland, OR",
];

export const RANDOM_NAMES = [
  "Liam Neeson",
  "Sophia Loren",
  "Noah Clark",
  "Olivia Vance",
  "Oliver Twist",
  "Emma Frost",
  "Lucas Kane",
  "Isabella Ross",
  "Elijah Wood",
  "Mia Wallace",
];
